### PR TITLE
Added support for specifying the classes of an input-text field.

### PR DESCRIPTION
**Pull request by sebinsua**
There was already support for this within the partials/forms/input-text-group template.

### CODE REVIEW

**Comment by sebinsua** [comment]
Is this okay?

It is consistent with the variable in the template, but it is not consistent with the 'display' class that is passed into radio-form-group elsewhere.

**Comment by lennym** [comment]
Could you use `className` instead of `class` - `class` is a reserved word so will make writing configuration more difficult.

**Comment by sebinsua** [comment]
Okay.

**Comment by lennym** [comment]
I'm actually slightly surprised that the addition to `inputText` didn't barf needing `class` to be quoted, but ¯\_(ツ)_/¯

**Pull request merged**
