### PR TITLE
Update dependencies, add code coverage, update linting

### PR DESCRIPTION
**Pull request by HughePaul**
Update to latest dependencies,
Add Snyk vulnerability check,
Update linting rules and some code to match,
Add editor config,
Add Istanbul and code coverage reporting but don't enforce in CI yet,
Test on node 4 and 6

### CODE REVIEW

**Comment by gavboulton** [comment]
This looks fine to me. Could someone else take a look too please.

**Comment by gavboulton** [comment]
@easternbloc @JoeChapman @joefitter @daniel-ac-martin?

**Comment by easternbloc** [comment]
Ha, I commented on this but my last two comments on github just vanished 💨

**Comment by joefitter** [comment]
@easternbloc I had a similiar issue yesterday - GH was having issues towards the end of the afternoon - I pushed to branches and they didn't show up until this morning. Looking at this now

**Comment by joefitter** [comment]
This LGTM but I do think that each HMPO repo should share the same .eslintrc configs - if we update it here, it should be updated everywhere. Have you guys looked at https://github.com/UKHomeOffice/eslint-config-homeoffice? You can extend from this and override the indentation & object padding etc? Or perhaps fork the repo and update with your defaults? It would end up with your .eslint files being something like

.eslintrc
```yml
extends:
  - "homeoffice/config/default"
```

test/.eslintrc
```yml

extends:
  - '../.eslintrc'
  - 'homeoffice/config/testing'

globals:
 +  request: true
 +  response: true
 +  StubController: true
```

**Comment by gavboulton** [comment]
I agree that we should start sharing linting. The HO eslint module is still using version 0 of eslint but we could investigate updating it.

**Comment by joefitter** [comment]
Yes good point - I'll add an issue to the repo

**Comment by joefitter** [comment]
I wasn't adding a blocker to this PR being merged BTW, looks fine to me. Just something to note perhaps once the version of eslint has been updated

**Pull request merged**
