### PR TITLE
Move the error message below the label and hint

### PR DESCRIPTION
**Pull request by shepda**
GOV.UK elements suggests that the error message for a field should be below the label and the hint, see http://govuk-elements.herokuapp.com/errors/. 

Currently `passports-templates-mixins` puts the error message for the `radio-group` mixin above the legend and this PR moves it to the correct position.

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
Looking at https://github.com/UKHomeOffice/passports-template-mixins/blob/master/partials/forms/input-text-group.html it would appear that this is a more widespread problem than just the radio groups. (Unless there is some CSS magic going on there.)

In fact, for input-text-group it seems that we only move it below the hint for screen readers.

@gavboulton: What do you think?

**Comment by gavboulton** [comment]
I'm happy with moving to this updated pattern but we should be consistent across input types. As @daniel-ac-martin has indicated, we can remove the visually hidden elements (and also remove the aria-hidden attributes from the moved elements) in input-text-group.html and select.html.

**Comment by roc** [comment]
@gavboulton @daniel-ac-martin merge this one then let's do another PR for consistency?

**Comment by gavboulton** [comment]
Let's do it all together.

**Pull request merged**
