### PR TITLE
Add hint text support to select partials

### LINKED ISSUE #51: Hint text for select fields
The current [select partial](https://github.com/UKHomeOffice/passports-template-mixins/blob/master/partials/forms/select.html) doesn't include the option to add hint text.

### PR DESCRIPTION
**Pull request by teneightfive**
Add hint text support for select partials.

Fixes #51

### CODE REVIEW

**Comment by gavboulton** [comment]
This looks good @teneightfive. Can you add a couple of more tests like https://github.com/UKTradeInvestment/passports-template-mixins/blob/select-hint-text/test/spec.index.js#L157-L182 please.

**Comment by gavboulton** [comment]
Thanks @teneightfive. hmpo-template-mixins@3.6.0 published.

**Comment by teneightfive** [comment]
@gavboulton Thanks. What's the release process for getting changes in these libraries published to HOF?

**Comment by gavboulton** [comment]
A caret range is set in HOF for this module so, as this has only been a minor update, it should update when you do a fresh `npm install`.

**Comment by easternbloc** [comment]
@teneightfive if for some reason you have any issues with updates in HOF just raise and issue and we can make version bumps accordingly.

**Comment by teneightfive** [comment]
@gavboulton @easternbloc thanks

**Comment by teneightfive** [comment]
Just tried to do a fresh install to get 3.6.0 but realised HOF has a shrinkwrap file which pins this module to 3.5.0. Will raise an issue on HOF to bump a version.

**Comment by easternbloc** [comment]
Ah yeah we do that to guarantee releases. Hah! OK I'll make a version bump of hof for you. 2mins

**Comment by easternbloc** [comment]
@teneightfive 3.1.0 is now on npm. Sorry my time perception was a little out there.

**Comment by teneightfive** [comment]
Haha. No worries. Thanks

**Pull request merged**
