### PR TITLE
Input code

### PR DESCRIPTION
**Pull request by gavboulton**
The postcode input is also being used for the invitation code. Update this to reflect this.

### CODE REVIEW

**Comment by lennym** [comment]
Why not just set the `className` instead of adding an extra layer of abstraction via `code`?

**Comment by gavboulton** [comment]
That would be easier!

**Comment by gavboulton** [comment]
Updated.

**Comment by lennym** [comment]
Just be sure to publish this as a minor version update and not a patch as it is a breaking change to the API.

**Comment by gavboulton** [comment]
Will do.

**Pull request merged**
