### PR TITLE
If an option label translation is returned as `undefined` set it as an empty string.

### PR DESCRIPTION
**Pull request by gavboulton**
@easternbloc @JoeChapman

### CODE REVIEW

**Comment by easternbloc** [comment]
@gavboulton test?

**Comment by gavboulton** [comment]
I can add a test.

**Comment by easternbloc** [comment]
yes please :)

**Comment by gavboulton** [comment]
Test added.

**Comment by easternbloc** [comment]
:+1:

**Comment by gavboulton** [comment]
Published at v3.2.1.

**Pull request merged**
