### PR TITLE
- pass autocomplete option or default

### PR DESCRIPTION
**Pull request by JoeChapman**
Closes [issues/43](https://github.com/UKHomeOffice/passports-template-mixins/issues/43)

### CODE REVIEW

**Comment by timgent** [comment]
Looks good to me

**Comment by easternbloc** [comment]
@gavboulton I hope this doesn't impact you this PR will default autocomplete to false is that OK?

**Comment by gavboulton** [comment]
@easternbloc @timgent @JoeChapman 

I've just noticed that it's been merged.

It's not a good idea to code something that defaults to an unsupported value for one browser. If I want to use any future versions of this module I will have to set `autocomplete: 'false'` for almost every field.

**Comment by easternbloc** [comment]
@JoeChapman @timgent @gavboulton I'll have another stab at this...

**Comment by gavboulton** [comment]
Thanks @easternbloc 

Setting a custom autocomplete attribute is fine, but if it's not set in the fields config then don't add it to the template. This way the browser default option or form level setting will be respected.

**Comment by easternbloc** [comment]
Different approach in #46

**Pull request merged**
