### PR TITLE
Add an `inexact-date` mixin that only displays the month and year, i.e. March 2015.

### PR DESCRIPTION
**Pull request by gavboulton**

### CODE REVIEW

**Comment by lennym** [comment]
What is this doing that the existing `input-date` with the `inexact` flag is not?

It seems like another way to do the same thing.

**Comment by gavboulton** [comment]
This is used when displaying a date. Passing a date into the `date` mixin without a day displays it as the first day of the month.

**Comment by lennym** [comment]
Gotcha.

I think a better way to do this might be to be able to add a format to the arguments rather than spin up new mixins for every possible date format we might ever use.

**Comment by gavboulton** [comment]
So do something like `{{#date}}2015-03 no-day{{/date}}`?

**Comment by lennym** [comment]
Roughly yes. I'd just make the format an actual format string though, so there's no some abstraction layer of key => format mappings to navigate - it will just be obvious what format you're getting.

I'd also make the separator a pipe instead of a space because otherwise date formats with spaces in will be liable to mess up.

**Comment by gavboulton** [comment]
Awesome.

**Pull request closed without merging**
